<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Jan</name>
   <tag></tag>
   <elementGuidId>69a7f476-6154-4fdb-97df-bf9ecbb4536b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.month.focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>16e2babc-2b20-41a3-bc9d-6877e3f4ed49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>month focused</value>
      <webElementGuid>f9935b6f-f0bf-42da-81f9-93d1fbe16039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jan</value>
      <webElementGuid>d04c8dfa-c312-497b-894b-f7cda6796a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;datepicker datepicker-dropdown dropdown-menu datepicker-orient-left datepicker-orient-top&quot;]/div[@class=&quot;datepicker-months&quot;]/table[@class=&quot;table-condensed&quot;]/tbody[1]/tr[1]/td[1]/span[@class=&quot;month focused&quot;]</value>
      <webElementGuid>490fd6b3-de21-4f02-a808-2bb3919b9e85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>b7f15e42-7f7a-4d9f-9dfa-027e97687a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Jan' or . = 'Jan')]</value>
      <webElementGuid>d0aa5d75-398d-44b0-a87e-d96786eda075</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
